### ISSUE TITLE
Add ext2simg

### ISSUE THREAD

**Issue by yuvadm** [anestisb/android-simg2img#10]
Would it be possible to add the ext2simg utility to this repo? It was until very recently part of the Android FS tools, and has now made it [upstream](https://git.kernel.org/pub/scm/fs/ext2/e2fsprogs.git/tree/contrib/android/ext2simg.c)

**Comment by anestisb** [comment]
Xmm, I don't see this one happening as part of this project since it requires fetching and building the entire `<AOSP>/external/e2fsprogs/lib/ext2fs`. Maybe a different project.
