### ISSUE TITLE
Compilation fix for MinGW/MSYS2 under Windows

### ISSUE THREAD

**Issue by 0xABD** [anestisb/android-simg2img#16]
Under Windows there is no sysconf(_SC_PAGESIZE), so to compile the project the quick&dirty fix is to use: 
```CFLAGS='-DUSE_MINGW -Dsysconf\(_SC_PAGESIZE\)=4096' LDFLAGS=-lasprintf mingw32-make```

**Comment by anestisb** [comment]
Thanks for reporting. Fixed in https://github.com/anestisb/android-simg2img/commit/223e415fb3b89c057e18c6655b034a1db60a21de.
