### ISSUE TITLE
Error when running simg2img

### ISSUE THREAD

**Issue by MalteToenjes** [anestisb/android-simg2img#18]
Hey, when I try to run  simg2img with userdata.img I got this error:

> Invalid sparse file format at header magi
Failed to read sparse file

I used an Android emulation with API28...can you help  me with this? Also when I run "file userdata.img" it returns >>data

**Comment by anestisb** [comment]
If file returns something other than Android sparse image, it makes sense for the tool not being able to parse it. So either the userdata.img you have is corrupted, or you have something customized in your environment. How did you obtain the userdata.img?

**Comment by Hubertyori** [comment]
I got the same issue could you help me to fix it?

**Comment by Sylend0** [comment]
This error shows up even if it's an Android img.

``file rootfs.img 
rootfs.img: Android bootimg, kernel (0x8000), ramdisk (0x1000000), page size: 4096, cmdline (mobile.root=UUID=6806e925-9daf-410a-a5d1-42b3036f543f mobile.qcomsoc=qcom/sdm845 mobile.vendor=oneplus mobile.model=fajita init)``
