### ISSUE TITLE
why ext2 ? not ext4

### ISSUE THREAD

**Issue by wv1124** [anestisb/android-simg2img#19]
wv@wv-mint:~/android/N960U$ file system.img
system.img: Linux rev 1.0 ext2 filesystem data (mounted or unclean), UUID=e47eeda7-b9a3-5aaa-9b6c-f0e5d865e7ef, volume name "system" (extents) (large files) (huge files)

**Comment by anestisb** [comment]
Some older low-spec Android devices preferred ext2 for performance reasons (e.g. no journaling) and lower writes (less reliable flash storages). To be honest I haven't seen/tested any system.img that is a sparse ext2. But from your output it seems that is a raw ext2 image and not a sparse one, thus no reason to run the tool. Just straight mount it to loopback.

**Comment by neo1949** [comment]
`system.img` generated from [MIUI12 ROM](http://bigota.d.miui.com/V12.0.3.0.QGHCNXM/miui_PHOENIX_V12.0.3.0.QGHCNXM_4814c5bed0_10.0.zip) is ext2 format:
```
system.img: Linux rev 1.0 ext2 filesystem data, UUID=4729639d-b5f2-5cc1-a120-9ac5f788683c (extents) (large files) (huge files)
```

**Comment by HassanMirza01** [comment]
i was able to mount normal MIUI 12 system.img files with ext4 format, but ext2 imgs are unable to mount... it says wrong fs type, bad option, bad superblock on /dev/loop16, missing codepage or helper program, or other error.

Any help ??

**Comment by neo1949** [comment]
> i was able to mount normal MIUI 12 system.img files with ext4 format, but ext2 imgs are unable to mount... it says wrong fs type, bad option, bad superblock on /dev/loop16, missing codepage or helper program, or other error.
> 
> Any help ??

Use [nlitsme/extfstools](https://github.com/nlitsme/extfstools) to extract system.img
