### ISSUE TITLE
Android10 system.img not mountable on Ubuntu and OS X

### ISSUE THREAD

**Issue by 7homasSutter** [anestisb/android-simg2img#27]
Hi there,

First of all, thanks for this awesome tool! It's a great!
I was trying to mount some Android10 system.img files, but it seems that the converted simg2img images for Android10 can't be mounted on Linux and OS X. I converted the system.img with simg2img, which seems to run through without any problem. However, as soon as I try to mount an error on Ubuntu occurs.

On Ubuntu I get the following mount error:
```
simg2img ./system.img ./system.raw.img
sudo mount ./system.raw.img ./mnt
mount: /home/ubuntu/test/sargo-qq2a.200501.001.a3/mnt: wrong fs type, bad option, bad superblock on /dev/loop4, missing codepage or helper program, or other error.
```
Which is not really helpful, so I tried it on OS X (10.14.6) as well.

On OS X I can mount the image with ext4fuse, but the files within the image are not readable. I can see the file-system structure, but it seems that somehow the permissions can't be loaded or something and therefore I have no access to the files.

Could someone take a look at this? I tried several Android10 Firmware images from the official [Google repo](https://developers.google.com/android/images) other images (<=9) work fine.

Best Regards,

Tom

**Comment by gittastic** [comment]
Hey Tom, this previous issue may be related: https://github.com/anestisb/android-simg2img/issues/17

I have been using the read-only mount as a workaround to read from them since, but i think there is a proper fix in the above link.

`sudo ./simg2img system.img sys.raw
sudo mount -t ext4 -o loop sys.raw sys/`

**Comment by 7homasSutter** [comment]
Oh wow, thanks! I could have seen this...
It works with read-only: `sudo mount -o ro ./system.raw.img ./mnt`
As mentioned in the other issue the read-write does not work at the moment and therefore I couldn't mount it with (`sudo mount -o rw ./system.raw.img ./mnt`).
