### ISSUE TITLE
Android 11 Support

### ISSUE THREAD

**Issue by kubo6472** [anestisb/android-simg2img#29]
I may finally understand why my android 11 image conversion keeps failing due to "bad magic". What is needed to make this compatible with the new android 11? Because right now, I am unable to try it in DSU.

**Comment by fO-000** [comment]
Maybe your `system.img` has already been unsparsed, If the result of the `file system.img` is

```txt
system.img: Linux rev 1.0 ext2 filesystem data, ...
```

or

```txt
system.img: Linux rev 1.0 ext4 filesystem data, ...
```
