### ISSUE TITLE
Motorola sparse images not mountable

### ISSUE THREAD

**Issue by 7homasSutter** [anestisb/android-simg2img#30]
Hi there,

After processing Motorola images with simg2img it seems that these files can't be mounted correctly. The mount operation on OS X and Linux works, but the files in the mounted directory can't be listed/accessed. 

Example Firmware Files from [Motostockrom](https://motostockrom.com/page/4)
- [motorola-one-xt1941](https://motostockrom.com/motorola-one-xt1941-3)
- [motorola-moto-e4-xt1762](https://motostockrom.com/motorola-moto-e4-xt1762-ds)

After investigating I found some threads and scripts ([1](https://forum.xda-developers.com/showthread.php?t=2608287), [2](https://github.com/Akianonymus/Firmware_Extraction), [3](https://gist.github.com/TwizzyIndy/8319d240a326a19422a97b998610a693), [4](https://gist.github.com/erfanoabdi/7ff14d614f4919fee5159fccd7885370)) which mention the same problem. They all remove some magic bytes ('\x53\xEF') from the header of the file, but none of the scripts I found worked for me. I tried the following:

Attempt 1 with simg2img:
```
simg2img system.img_sparsechunk.0 system.raw.img
mount -o loop system.raw.img ./test/
mount -o loop -t auto system.raw.img ./test/
mount -o ro system.raw.img ./test/
mount -o ro -t auto system.raw.img ./test/

#  I don't know if the * makes any difference, tested it anyways.
simg2img system.img_sparsechunk.* system.raw.img
mount -o loop system.raw.img ./test/
mount -o loop -t auto system.raw.img ./test/
mount -o ro system.raw.img ./test/
mount -o ro -t ext4 system.raw.img ./test/
mount -o ro -t auto system.raw.img ./test/

OS X
simg2img system.img_sparsechunk.* system.raw.img
ext4fuse -o allow_other,defer_permissions system.raw.img ./test/ 
Errors - Depending on the file:
   - OS X finder hangs
   - Shows "Partition doesn't contain EXT4 filesystem"
```

Attempt 2 - testing the script from [2]:
```
simg2img system.img_sparsechunk.0 system.raw.img
img2raw system.raw.img system.raw.raw
mount -o ro system.raw.raw ./test/ --> Error
simg2img system.raw.raw system2.raw.img
mount -o ro system.raw.raw ./test/ --> Error
```
I tested this with around ten samples and all show the same behaviour. Is there a way to convert Motorola firmware files with simg2img so that they are mountable? Do I need to add some special parameters to mount these files?

Thanks for any help in advance!

Best Regards

Tom

**Comment by Ionic** [comment]
You probably don't care about this any longer, but for posterity...

Try [ReFirmLabs/binwalk](https://github.com/ReFirmLabs/binwalk) to get the actual starting location of the file system after using `simg2img` on it.

Example:

```text
% binwalk system.raw.img                                                                                                                           
                                                                                                                                                                                                          
DECIMAL       HEXADECIMAL     DESCRIPTION                                                                                                                                                                 
--------------------------------------------------------------------------------                                                                                                                          
131072        0x20000         Linux EXT filesystem, blocks count: 604807, image size: 619322368, rev 2.0, ext4 filesystem data, UUID=da594c53-9beb-f85c-85c5-cedf76547654, volume name "system"
[...]
% mount -o loop,ro,offset=0x20000 system.raw.img mount
%
```

Also explained on [Android SE](https://android.stackexchange.com/a/234806).

There's nothing wrong with `simg2img`, it's just that Motorola likes to prepend some data that is not part of the actual file system.

> [Imaginary quote]
> Okay, but I tried to get the offset using `grep`, as suggested in the links I provided and this didn't give me the correct offset.

Yes, that's true. Let me give an example:

```text
% LANG=C grep -aobP -m1 '\x53\xEF' ../system.raw.img | head -1 | gawk '{print $1 - 1080}'
228906959
```

Looks weird. The offset is huge, that can't be right.

The reason for this is... encodings! If your locale is UTF-8 based (which should typically be the case), then the input will be parsed as UTF-8. `\x53\xEF` isn't valid UTF-8, though (`\xEF` indicates a three-byte sequence, but no more bytes follow), so all bets are off.

Execute `grep` in byte mode and it'll work correctly:

```text
% LANG=C LC_ALL=C grep -aobP -m1 '\x53\xEF' ../system.raw.img | head -1 | gawk '{print $1 - 1080}'
131072
```

This offset looks much better!

If this solves your issue, please remember to close this report.
