### ISSUE TITLE
License and Tag

### ISSUE THREAD

**Issue by wltjr** [anestisb/android-simg2img#7]
You may want to consider adding a License to the repo and a tag would be nice. I saw the files are licensed but the repo is missing a License/Copyright file. Github doesn't show the license of the repo because such file is missing. Both are minor, but if you do not mind. Thank you!

**Comment by anestisb** [comment]
I don't see any reason for either.

**Comment by ollieparanoid** [comment]
I'd also like to see tags for the repository, so we could [package it properly](https://github.com/postmarketOS/pmbootstrap/issues/299) in Linux distributions.

@anestisb: Could you please reconsider that?

**Comment by anestisb** [comment]
OK, will take care of it today.

**Comment by anestisb** [comment]
Should be OK now. Let me know if that works for you.

**Comment by ollieparanoid** [comment]
Perfect, thank you very much!
