### ISSUE TITLE
openssl 1.1 compatibility

### ISSUE THREAD

**Issue by maertsen** [anestisb/android-simg2img#8]
Compiling against openssl 1.1 results in the following errors

```
generate_verity_key.c: In function ‘convert_to_mincrypt_format’:
generate_verity_key.c:57:19: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
     BN_copy(n, rsa->n);
generate_verity_key.c:75:37: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
     pkey->exponent = BN_get_word(rsa->e);
```

This is a result of [api changes](https://wiki.openssl.org/index.php/1.1_API_Changes)

The following patch is a dirty fix; I'm not sure how you would like to handle backward compatibility.

```
diff --git a/generate_verity_key.c b/generate_verity_key.c
index 0da978f..609ca8a 100644
--- a/generate_verity_key.c
+++ b/generate_verity_key.c
@@ -53,8 +53,12 @@ static int convert_to_mincrypt_format(RSA *rsa, RSAPublicKey *pkey)
     BIGNUM* n = BN_new();
     BIGNUM* n0inv = BN_new();
 
+    const BIGNUM *cur_n;
+    const BIGNUM *cur_e;
+    RSA_get0_key(rsa, &cur_n, &cur_e, NULL);
+
     BN_set_bit(r32, 32);
-    BN_copy(n, rsa->n);
+    BN_copy(n, cur_n);
     BN_set_bit(r, RSANUMWORDS * 32);
     BN_mod_sqr(rr, r, n, ctx);
     BN_div(NULL, rem, n, r32, ctx);
@@ -68,7 +72,7 @@ static int convert_to_mincrypt_format(RSA *rsa, RSAPublicKey *pkey)
         BN_div(n, rem, n, r32, ctx);
         pkey->n[i] = BN_get_word(rem);
     }
-    pkey->exponent = BN_get_word(rsa->e);
+    pkey->exponent = BN_get_word(cur_e);
 
     ret = 0;
```

**Comment by anestisb** [comment]
I think you have mixed the projects. The code you're referencing is not part of the simg2img tool (also check [this](http://androidxref.com/7.0.0_r1/xref/system/extras/verity/generate_verity_key.c#convert_to_mincrypt_format)). It's part of the verity tools and is unrelated to this repo.

Just to help you further, AOSP is using boringssl for quite some time. That policy includes libcrypto-host tools (more info [here](http://androidxref.com/7.0.0_r1/xref/external/boringssl/Android.mk#74)). So if you build standalone host tools you need to use compatible libs or fork AOSP crypto libs.
