### ISSUE TITLE
Error while excecuting make

### ISSUE THREAD

**Issue by nmantas** [anestisb/android-simg2img#9]
While excecuting make this error comes up:
`sudo make `
`cc -c -O2 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -Iinclude output_file.c -o `
`output_file.o`
`output_file.c:30:18: fatal error: zlib.h: No such file or directory`
`#include <zlib.h>`
`               ^      `
`compilation terminated. `
`Makefile:69: recipe for target 'output_file.o' failed `
`make: *** [output_file.o] Error 1`

make version : make-4.0-5.54.x86_64
gcc version : gcc-4.8-9.61.x86_64

**Comment by anestisb** [comment]
You don't need run make as super-user. Remove the sudo part and try again.

If you still have a problem it means that `libz` is not installed or visible (correct paths not set) on your workstation. So you need to install it and/or configure it properly.

**Comment by nmantas** [comment]
ok reinstalling zlib did the trick. Thanks
